export const MOCK_RESTAURANTS = [
  {
    id: 'r1',
    name: 'Savour Foods',
    cuisine: 'Pakistani',
    location: 'Blue Area, Islamabad',
    rating: 4.6,
    priceRange: 'PKR 800–1500',
    ambiance: ['family-friendly', 'casual'],
    popularDish: 'Peshawari Karahi',
    tags: ['halal', 'desi', 'karahi'],
    avgWaitMinutes: 25,
  },
  {
    id: 'r2',
    name: 'Monal Restaurant',
    cuisine: 'Pakistani / Continental',
    location: 'Margalla Hills, Islamabad',
    rating: 4.4,
    priceRange: 'PKR 1500–3000',
    ambiance: ['scenic', 'romantic', 'outdoor-seating'],
    popularDish: 'Grilled Chicken Platter',
    tags: ['view', 'upscale', 'date-night'],
    avgWaitMinutes: 35,
  },
  {
    id: 'r3',
    name: 'Bundu Khan',
    cuisine: 'Pakistani BBQ',
    location: 'F-7 Markaz, Islamabad',
    rating: 4.3,
    priceRange: 'PKR 1000–2000',
    ambiance: ['casual', 'family-friendly'],
    popularDish: 'Seekh Kebab',
    tags: ['bbq', 'grill', 'kebab'],
    avgWaitMinutes: 20,
  },
  {
    id: 'r4',
    name: 'Tuscany Courtyard',
    cuisine: 'Italian / Continental',
    location: 'F-6, Islamabad',
    rating: 4.5,
    priceRange: 'PKR 2000–4000',
    ambiance: ['quiet', 'romantic', 'upscale'],
    popularDish: 'Truffle Mushroom Pasta',
    tags: ['western', 'pasta', 'fine-dining'],
    avgWaitMinutes: 30,
  },
  {
    id: 'r5',
    name: 'Street 1 Cafe',
    cuisine: 'Fusion / Cafe',
    location: 'DHA Phase 2, Islamabad',
    rating: 4.2,
    priceRange: 'PKR 600–1200',
    ambiance: ['casual', 'quiet', 'work-friendly'],
    popularDish: 'Loaded Fries',
    tags: ['cafe', 'budget', 'lunch'],
    avgWaitMinutes: 15,
  },
  {
    id: 'r6',
    name: 'China Town',
    cuisine: 'Chinese',
    location: 'G-9 Markaz, Islamabad',
    rating: 4.1,
    priceRange: 'PKR 900–1800',
    ambiance: ['family-friendly', 'casual'],
    popularDish: 'Kung Pao Chicken',
    tags: ['chinese', 'noodles', 'family'],
    avgWaitMinutes: 20,
  },
];

export const MOCK_MENUS = {
  r1: [
    { id: 'm1_1', name: 'Peshawari Karahi', price: 1200, description: 'Slow-cooked mutton in aromatic spices', category: 'Main', spiceLevel: 'medium' },
    { id: 'm1_2', name: 'Chapli Kebab', price: 450, description: '2 pieces with raita and naan', category: 'Starter', spiceLevel: 'mild' },
    { id: 'm1_3', name: 'Biryani', price: 650, description: 'Fragrant basmati with tender chicken', category: 'Main', spiceLevel: 'medium' },
  ],
  r2: [
    { id: 'm2_1', name: 'Grilled Chicken Platter', price: 1850, description: 'Flame-grilled breast with roasted veggies', category: 'Main', spiceLevel: 'mild' },
    { id: 'm2_2', name: 'Cheese Naan', price: 350, description: 'Stuffed with cheddar and mozzarella', category: 'Starter', spiceLevel: 'none' },
    { id: 'm2_3', name: 'Molten Lava Cake', price: 600, description: 'Decadent chocolate dessert served with ice cream', category: 'Dessert', spiceLevel: 'none' },
  ],
  r3: [
    { id: 'm3_1', name: 'Seekh Kebab', price: 800, description: '4 pieces of minced beef kebabs, grilled on charcoal', category: 'Main', spiceLevel: 'hot' },
    { id: 'm3_2', name: 'Chicken Boti', price: 900, description: 'Spiced boneless chicken chunks', category: 'Main', spiceLevel: 'medium' },
    { id: 'm3_3', name: 'Garlic Naan', price: 120, description: 'Freshly baked tandoori naan with garlic butter', category: 'Starter', spiceLevel: 'none' },
  ],
  r4: [
    { id: 'm4_1', name: 'Truffle Mushroom Pasta', price: 2200, description: 'Creamy fettuccine with mushrooms and white truffle oil', category: 'Main', spiceLevel: 'none' },
    { id: 'm4_2', name: 'Margherita Pizza', price: 1500, description: 'Classic mozzarella, basil, and tomato sauce crust', category: 'Main', spiceLevel: 'none' },
    { id: 'm4_3', name: 'Caesar Salad', price: 850, description: 'Crisp romaine lettuce with parmesan and creamy dressing', category: 'Starter', spiceLevel: 'none' },
  ],
  r5: [
    { id: 'm5_1', name: 'Loaded Fries', price: 750, description: 'Crispy fries topped with cheese sauce and jalapenos', category: 'Starter', spiceLevel: 'medium' },
    { id: 'm5_2', name: 'Beef Smash Burger', price: 1100, description: 'Double patty with cheddar, caramelized onions and secret sauce', category: 'Main', spiceLevel: 'mild' },
    { id: 'm5_3', name: 'Mint Margarita', price: 350, description: 'Refreshing blended mint and lime mocktail', category: 'Drinks', spiceLevel: 'none' },
  ],
  r6: [
    { id: 'm6_1', name: 'Kung Pao Chicken', price: 1400, description: 'Stir-fried chicken cubes with peanuts, veggies and chili', category: 'Main', spiceLevel: 'hot' },
    { id: 'm6_2', name: 'Egg Fried Rice', price: 800, description: 'Wok-tossed rice with scrambled eggs and green onions', category: 'Main', spiceLevel: 'none' },
    { id: 'm6_3', name: 'Chicken Corn Soup', price: 450, description: 'Warm comforting soup with shredded chicken and sweet corn', category: 'Starter', spiceLevel: 'none' },
  ],
};
